In [1]:
#Implementing basic mathematical operations (addition, subtraction, multiplication) using NumPy arrays.


In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
b=np.array([4,5,6])

In [5]:
addition_np=np.add(a,b)

In [6]:
addition_np

array([5, 7, 9])

In [10]:
subtraction_result = np.subtract(a, b)

In [11]:
subtraction_result

array([-3, -3, -3])

In [12]:
mul_result=np.multiply(a, b)

In [13]:
mul_result

array([ 4, 10, 18])